### PR TITLE
GD-129: Enable GdUnit C# support

### PR DESCRIPTION
**Pull request by MikeSchulze**

### CODE REVIEW

**Comment by GeorgeS2019** [comment]
Please give an estimation, when is a working alpha, beta and finally the 2.0 version.

**Comment by GeorgeS2019** [comment]
Please give an estimation, when is a working alpha, beta and finally the 2.0 version.

**Comment by MikeSchulze** [comment]
> Please give an estimation, when is a working alpha, beta and finally the 2.0 version.

It's hard to say, I'm working on it in my spare time.

First goal is to get a test running with repecting timeouts, paramized tests (fuzzing), orphan node detection.
- [x] basis type asserts
- [x] test executor
- [x] integrate in Godot to run c# tests
- [x] addapt command line tool to run c# tests  
- [x] paramized tests
  - [x] Fuzzer 
  - [x] iterations
  - [ ] seed   
- [x] orphan node detection
- [ ] handling test timeouts
- [ ] support async tests (yield, await)
- [ ] support of parallel suite execution

**Comment by MikeSchulze** [comment]
continue on https://github.com/MikeSchulze/gdUnit3/pull/210

**Pull request closed without merging**
